// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/history.js', ['historyplus', 'historyplus.SearchController'], ['goog.Uri', 'goog.array', 'goog.date', 'goog.date.DateRange', 'goog.date.DateTime', 'goog.date.Interval', 'goog.dom', 'goog.dom.classes', 'goog.dom.query', 'goog.events', 'goog.i18n.DateTimeFormat', 'goog.i18n.DateTimeParse', 'goog.style', 'goog.ui.CustomButton', 'goog.ui.LabelInput', 'goog.ui.ToggleButton', 'goog.ui.decorate']);
